### PR TITLE
Fix gitter link

### PR DESCRIPTION
**Pull request by FrankHossfeld**
The link to the GWT Gitter/Matrix room is broken. This will fix it.

### CODE REVIEW

**Review by jnehlmeier — APPROVED** [review]

**Comment by bpetridean** [comment]
@FrankHossfeld I would squash the 5 commits into 1 before merging into master...low prio though

**Comment by FrankHossfeld** [comment]
> @FrankHossfeld I would squash the 5 commits into 1 before merging into master...low prio though

Not sure how to do that with the browser.  But the one who merges ist can say squash and merge.

**Comment by niloc132** [comment]
Yes, we default to squash commit merges (and the title/description become the commit message), in keeping with the basic idea from gerrit, to keep history clear and linear, and keep the author’s focus on the content for any given PR.

**Comment by FrankHossfeld** [comment]
I'll do a new PR

**Pull request merged**
