### PR TITLE
Fix issue #9804

### PR DESCRIPTION
**Pull request by DRAWSVG**
Checks that the stack is not empty during the loop. Fix issue #9804

Thanks for your contribution to the GWT Project!

Please make sure your pull request has a short, concise title, and a
clear description that can be used as a commit message for the entire
pull request when it is squashed into a single commit.

The message should end with a reference to the github issue being
addressed in this pull request, e.g. "Fixes #42" to close the linked
issue, or "Partial #42" to indicate that this merge will address it,
but that it isn't ready to be closed yet.

### CODE REVIEW

**Comment by DRAWSVG** [comment]
Fix three exceptions in StoryRecorder 
EmptyStackException lines 172, 300 
StringIndexOutOfBoundsException line 272

**Comment by zbynek** [comment]
@DRAWSVG you mention 3 exceptions, but your proposed fix only adds one check, do you want to work on this?

**Comment by niloc132** [comment]
The PR has been closed and not reopened, I'm guessing they are still working on it?

**Comment by DRAWSVG** [comment]
Hello,
To fix the issue I made 3 corrections in the class StoryRecorder:

Line 172 EmptyStackException in **analyzeFragment** method :
 // Infer dependency information
      **while (!dependencyScope.isEmpty() **&& !dependencyScope.peek().range.contains(range)**) {**
        /*
         * Pop frames until we get back to a container, using this as a chance
         * to build up our list of non-overlapping Ranges to report back to the
         * user.
         */
        popAndRecord(dependencyScope, fragment);
      }

Line 272 StringIndexOutOfBoundsException in escapeXml from **emitStory** method :
      builder.append("\">");
      SizeMapRecorder.escapeXml(jsCode, start, **Math.min(end,jsCode.length())**, false, builder);
      builder.append("</storyref>\n</story>\n");

Line 300  EmptyStackException in **popAndRecord** method:
 if (lastEnd < toStore.getStart() **&& !dependencyScope.isEmpty()**) {
      Range newRange = new Range(lastEnd, toStore.getStart());
      assert !dependencyScope.isEmpty();
      SourceInfo gapInfo = dependencyScope.peek().info;
      recordStory(gapInfo, fragment, newRange.length(), newRange);
      lastEnd += newRange.length();
    }

I validated these corrections with my project (drawsvg) which has more than 3000 classes and 60 split points.

Are sure that these corrections are not **all** in my PR ?
Seems to be OK to me, but I may have mishandled as this is my first PR

Regards
Joseph

**Comment by niloc132** [comment]
Your `main` branch does have several changes to it
https://github.com/DRAWSVG/gwt/commit/79c202f48c143ce910d8cc319f0b83b4b672f690

but since this PR is closed, it isn't being updated as you make changes. Do you want to reopen it?

**Comment by zbynek** [comment]
This can be closed in favor of #9808

**Pull request closed without merging**
